import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/router";
import styles from "@/styles/Home.module.scss";
import Header from "@/components/Header";
import Button from "@/components/Button";

export default function Home() {
  const router = useRouter();
  const menuData = [
    { href: "/items", menuName: "아이템" },
    { href: "/additem", menuName: "아이템추가" },
    { href: "/additem", menuName: "자유게시판" },
  ];
  return (
    <>
      <Head>
        <title>판다마켓</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header menuData={menuData} />
      <main>
        <div className={styles.main_visual}>
          <div className={styles.main_visual_text}>
            <p>일상의 모든 물건을 거래해 보세요</p>
            <Button
              text={"구경하러 가기"}
              className={"btn_style"}
              onClick={() => router.push("/items")}
            />
          </div>
        </div>
        <div className={`${styles.main_content} ${styles.padding_content}`}>
          <div className={styles.main_content_item}>
            <div className={styles.content_img}>
              <Image
                src="/img_home_01.png"
                alt="인기상품을확인해보세요"
                width="588"
                height="444"
              />
            </div>
            <div className={styles.content_txt}>
              <span>Hot item</span>
              <h2>인기 상품을 확인해 보세요</h2>
              <p>가장 HOT한 중고거래 물품을 판다 마켓에서 확인해 보세요</p>
            </div>
          </div>
          <div className={styles.main_content_item}>
            <div className={styles.content_img}>
              <Image
                src="/img_home_02.png"
                alt="인기상품을확인해보세요"
                width="588"
                height="444"
              />
            </div>
            <div className={styles.content_txt}>
              <span>Search</span>
              <h2>구매를 원하는 상품을 검색하세요</h2>
              <p>가장 HOT한 중고거래 물품을 판다 마켓에서 확인해 보세요</p>
            </div>
          </div>
          <div className={styles.main_content_item}>
            <div className={styles.content_img}>
              <Image
                src="/img_home_01.png"
                alt="인기상품을확인해보세요"
                width="588"
                height="444"
              />
            </div>
            <div className={styles.content_txt}>
              <span>Register</span>
              <h2>판매를 원하는 상품을 등록하세요</h2>
              <p>가장 HOT한 중고거래 물품을 판다 마켓에서 확인해 보세요</p>
            </div>
          </div>
        </div>
      </main>
      <footer className={styles.footer}>
        <div className={styles.footer_wrapp}>
          <p>©codeit - 2024</p>
        </div>
      </footer>
    </>
  );
}
