import React, { useEffect, useState } from "react";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "@/styles/Home.module.scss";
import Button from "@/components/Button";

interface Input {
  email: string;
  password: string;
}

interface Message {
  emailMsg: string;
  passwordMsg: string;
}

interface Valid {
  emailValid: boolean;
  passwordValid: boolean;
}

const Login = () => {
  const [input, setInput] = useState<Input>({
    email: "",
    password: "",
  });
  const [message, setMessage] = useState<Message>({
    emailMsg: "",
    passwordMsg: "",
  });

  const emailRegExp =
    /^[A-Za-z0-9]([-_.]?[A-Za-z0-9])*@[A-Za-z0-9]([-_.]?[A-Za-z0-9])*\.[A-Za-z]{2,3}$/;

  const onChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setInput({ ...input, [e.target.name]: e.target.value });
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    const { email, password } = input;
    if (emailRegExp.test(input.email) && input.password.length > 7) {
      //로극인 로직
      alert("로그인");
    } else {
      alert("유효한 이메일과 비밀번호를 입력해주세요.");
    }
  };

  const handleEmailError = () => {
    if (input.email.length < 1) {
      alert("이메일을 입력해주세요.");
    }
    setMessage({
      ...message,
      emailMsg: emailRegExp.test(input.email) ? "" : "잘못된 이메일입니다.",
    });
  };

  const handlePasswordError = () => {
    if (input.password.length < 1) {
      alert("비밀번호를 입력해주세요.");
    }
    setMessage({
      ...message,
      passwordMsg:
        input.password.length > 7 ? "" : "비밀번호 8글자 이상 입력해주세요.",
    });
  };

  return (
    <>
      <Head>
        <title>로그인</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <header className={styles.sign_header}>
          <h1>
            <Link href="/">
              <Image src="/logo.png" alt="로고" width="396" height="132" />
            </Link>
          </h1>
        </header>
        <div className={styles.sign_wrap}>
          <form onSubmit={handleSubmit}>
            <div className={styles.sign_input}>
              <label>이메일</label>
              <input
                placeholder="이메일을 입력해주세요"
                value={input.email}
                name="email"
                onChange={onChange}
                onBlur={handleEmailError}
              />
              <span>{message.emailMsg}</span>
            </div>
            <div className={styles.sign_input}>
              <label>비밀번호</label>
              <input
                type="password"
                placeholder="비밀번호를 입력해주세요"
                value={input.password}
                name="password"
                onChange={onChange}
                onBlur={handlePasswordError}
              />
              <span>{message.passwordMsg}</span>
            </div>
            <Button text={"로그인"} className={"btn_style"} />
          </form>
        </div>
        <div className={styles.sign_notice}>
          <p>
            판다마켓이 처음이신가요? <Link href="./signup">회원가입</Link>
          </p>
        </div>
      </main>
    </>
  );
};

export default Login;
